# permissions for end users to edit httproutebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httproutebinding-editor-role
rules:
- apiGroups:
  - virtualserviceroute.shibataka000.com
  resources:
  - httproutebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - virtualserviceroute.shibataka000.com
  resources:
  - httproutebindings/status
  verbs:
  - get
