# permissions for end users to view httproutebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httproutebinding-viewer-role
rules:
- apiGroups:
  - virtualservicecomponent.shibataka000.com
  resources:
  - httproutebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - virtualservicecomponent.shibataka000.com
  resources:
  - httproutebindings/status
  verbs:
  - get
